Write-Host "___________"
Write-Host "< thank you >"
Write-Host " -----------"
Write-Host "        \   ^__^"
Write-Host "         \  (oo)\_______"
Write-Host "            (__)\       )\/\"
Write-Host "                ||----w |"
Write-Host "                ||     ||"
